/*
 * LineProperties.java
 *
 * Created on 11 July 2005, 14:02
 */

package frg.spiro;

import java.awt.event.*;
import javax.swing.*;
import frg.gui.*;
import frg.util.NumberUtils;

/**
 *
 * @author  fgrebenicek
 */
public class LineProperties extends javax.swing.JPanel {
  
  CssResourceMan rsc;
  App application;
  
  /** Creates new form LineProperties */
  public LineProperties(App parent) {
    this.application = parent;
    rsc = new CssResourceMan(getClass().getName());
    initComponents();
    complete();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    java.awt.GridBagConstraints gridBagConstraints;

    lbLine = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    lbLine.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbLine.setText("Line");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(lbLine, gridBagConstraints);

  }//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lbLine;
  // End of variables declaration//GEN-END:variables
  JColorButton btLineColor;
  JColorButton btFillColor;
  JTextField tfLineWidth;
 
  private void complete() {
    lbLine.setText(rsc.getString("lbLine-text"));
    btLineColor = new JColorButton(rsc.getString("btLineColor-title"));
    btFillColor = new JColorButton(rsc.getString("btFillColor-title"));
    btFillColor.setColor(java.awt.Color.white);
    tfLineWidth = new JTextField();
    tfLineWidth.setToolTipText(rsc.getString("tfLineWidth-tip"));
    tfLineWidth.setColumns(3);
    ////
    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.insets = new java.awt.Insets(2,2,2,2);
    add(tfLineWidth, gbc);
    add(btLineColor);
    add(btFillColor);
    LineListener listener = new LineListener();
    tfLineWidth.addActionListener(listener);
    btLineColor.setSelectionListener(listener);
    btFillColor.setSelectionListener(listener);
  }
  
  public void fireProjectChange() {
    tfLineWidth.setText(""+application.drawing.getLineWidth());
    btLineColor.setColor(application.drawing.getLineColor());
    btFillColor.setColor(application.drawing.getFillColor());
  }
  
  public class LineListener implements ActionListener {
    
    public void actionPerformed(ActionEvent e) {
      if (e.getSource() == btLineColor) 
        application.drawing.setLineColor(btLineColor.getColor());
      else if (e.getSource() == btFillColor) 
        application.drawing.setFillColor(btFillColor.getColor());
      else if (e.getSource() == tfLineWidth)
        application.drawing.setLineWidth(
          (float) NumberUtils.parseDouble(tfLineWidth.getText(), application.drawing.getLineWidth()));
      application.editPerformed(e.getSource());
    }
  }
  
}
